#!/bin/sh
#
# This hook is invoked when a git-checkout[1] is run after having updated the worktree.
# The hook is given three parameters: the ref of the previous HEAD, the ref of the new HEAD (which may or may not have changed),
# and a flag indicating whether the checkout was a branch checkout (changing branches, flag=1) or a file checkout
# (retrieving a file from the index, flag=0). This hook cannot affect the outcome of git checkout.

# enable if rolling back from go-modules to vendoring with git-sub-modules
# ./git-submodule-checkout.sh
