FROM golang:1.10

WORKDIR /go/src/github.com/orbs-network/orbs-network-go/

ADD . /go/src/github.com/orbs-network/orbs-network-go/

RUN ./test.sh

RUN CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' main.go

