FROM golang:1.10-alpine

RUN apk add --no-cache gcc musl-dev

WORKDIR /go/src/github.com/orbs-network/orbs-network-go/

ADD . /go/src/github.com/orbs-network/orbs-network-go/

RUN env

RUN go env

ARG SKIP_TESTS

ARG SKIP_DEVTOOLS

RUN sh -x test.sh

RUN sh -x build-binaries.sh
