FROM golang:1.10-alpine

RUN apk add --no-cache gcc musl-dev

WORKDIR /go/src/github.com/orbs-network/orbs-network-go/

ADD . /go/src/github.com/orbs-network/orbs-network-go/

RUN sh -x test.acceptance.sh
