// Copyright 2019 the orbs-network-go authors
// This file is part of the orbs-network-go library in the Orbs project.
//
// This source code is licensed under the MIT license found in the LICENSE file in the root directory of this source tree.
// The above notice should be included in all copies or substantial portions of the software.

package committee_systemcontract

import (
	"encoding/binary"
	"github.com/orbs-network/orbs-contract-sdk/go/sdk/v1/env"
	"github.com/orbs-network/orbs-network-go/crypto/hash"
)

/**
 * via callSystemContract or sendTx the function returns the currently being generated block committee (prev refTime from lean helix, current generated by node)
 * via RunQuery the function returns the committee of the block that was closed (run query gets prev/current refTime from storage
 */
func getOrderedCommittee() [][]byte {
	return _orderList(env.GetBlockCommittee(), _generateSeed(env.GetBlockHeight()))
}

func _generateSeed(blockHeight uint64) []byte {
	seedBytes := make([]byte, 8)
	binary.LittleEndian.PutUint64(seedBytes, blockHeight)
	return seedBytes
}

func _orderList(addresses [][]byte, seed []byte) [][]byte {

	committeeSize := len(addresses)
	orderedCommitteeAddresses := make([][]byte, 0, committeeSize)
	random := seed
	accumulatedWeights, totalWeight := _calculateAccumulatedWeightArray(addresses)

	for j := 0; j < committeeSize; j++ {
		random = _nextRandom(random)
		curr := _getRandomWeight(random, totalWeight)

		for i := 0; i < committeeSize; i++ {
			if curr > accumulatedWeights[i] {
				continue
			}
			orderedCommitteeAddresses = append(orderedCommitteeAddresses, addresses[i])
			currWeight := _absoluteWeight(addresses[i])
			totalWeight -= currWeight
			accumulatedWeights[i] = 0
			for k := i + 1; k < committeeSize; k++ {
				if accumulatedWeights[k] != 0 {
					accumulatedWeights[k] -= currWeight
				}
			}
			break
		}
	}
	return orderedCommitteeAddresses
}

func _calculateAccumulatedWeightArray(addresses [][]byte) ([]int, int) {
	accumulatedWeights := make([]int, len(addresses))
	totalWeight := 0
	for i, address := range addresses {
		weight := _absoluteWeight(address)
		totalWeight += weight
		accumulatedWeights[i] = totalWeight
	}
	return accumulatedWeights, totalWeight
}

func _absoluteWeight(address []byte) int {
	return 1 << (_getMaxReputation() - getReputation(address))
}

func _nextRandom(random []byte) []byte {
	return hash.CalcSha256(random)
}

func _getRandomWeight(random []byte, maxWeight int) int {
	return int(binary.LittleEndian.Uint32(random[hash.SHA256_HASH_SIZE_BYTES-4:]) % uint32(maxWeight)) + 1
}
